// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcljwKwdnLDIy6RBqZhtWLGvOLMPTYE1w',
    appId: '1:159968952265:android:7d9e65e738dfeb6bd4f218',
    messagingSenderId: '159968952265',
    projectId: 'habesha-tax-app',
    storageBucket: 'habesha-tax-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjL-SO9mWmS3owXfXhSfH9bMwIBGuw2Sw',
    appId: '1:159968952265:ios:48a73685d36dedd5d4f218',
    messagingSenderId: '159968952265',
    projectId: 'habesha-tax-app',
    storageBucket: 'habesha-tax-app.firebasestorage.app',
    iosBundleId: 'com.example.habeshaTaxApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFLbIoHYBBJRBB3YPrzJV9nq0DZlYh8o',
    appId: '1:159968952265:web:0e1135962cfceb85d4f218',
    messagingSenderId: '159968952265',
    projectId: 'habesha-tax-app',
    authDomain: 'habesha-tax-app.firebaseapp.com',
    storageBucket: 'habesha-tax-app.firebasestorage.app',
    measurementId: 'G-2D0X5TPZ7M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjL-SO9mWmS3owXfXhSfH9bMwIBGuw2Sw',
    appId: '1:159968952265:ios:48a73685d36dedd5d4f218',
    messagingSenderId: '159968952265',
    projectId: 'habesha-tax-app',
    storageBucket: 'habesha-tax-app.firebasestorage.app',
    iosBundleId: 'com.example.habeshaTaxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFLbIoHYBBJRBB3YPrzJV9nq0DZlYh8o',
    appId: '1:159968952265:web:b2466f52476276eed4f218',
    messagingSenderId: '159968952265',
    projectId: 'habesha-tax-app',
    authDomain: 'habesha-tax-app.firebaseapp.com',
    storageBucket: 'habesha-tax-app.firebasestorage.app',
    measurementId: 'G-MKT73F3ZT7',
  );

}